apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
spec:
  capacity:
    storage: 3Gi               
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-hostpath"         
  hostPath:
    path: /data/mongo-repl/mongo-0
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-1
spec:
  capacity:
    storage: 3Gi               
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-hostpath" 
  hostPath:
    path: /data/mongo-repl/mongo-1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-2
spec:
  capacity:
    storage: 3Gi               
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-hostpath" 
  hostPath:
    path: /data/mongo-repl/mongo-2
  persistentVolumeReclaimPolicy: Retain
