apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath
provisioner: kubernetes.io/no-provisioner   # No dynamic provisioner; manual PV binding
volumeBindingMode: WaitForFirstConsumer     # Delay binding until a Pod is scheduled
